### ISSUE TITLE
No translation

### ISSUE THREAD

**Issue by 18skeltor** [Richie-Z/romajin#1]
This is a great extension but unfortunately it doesn't seem to be translating the text to English :(

The proxy is http://localhost:8080/, I didn't change anything, but I only get romaji

**Comment by Richie-Z** [comment]
@18skeltor 
Since the Spicetify extension runs in the browser then accessing Google Translate API requires a proxy for bypass the CORS issue. The quick solution to overcome that issue, is using [cors-anywhere](https://github.com/Rob--W/cors-anywhere).

Currently I don't have a server to host a cors-anywhere, but there is a demo to access cors-anywhere, you can request the demo in this [site](https://cors-anywhere.herokuapp.com/corsdemo) after that you can change the proxy from http://localhost:8080 to https://cors-anywhere.herokuapp.com/

**Comment by todayisyokult** [comment]
> @Richie-Z Since the Spicetify extension runs in the browser then accessing Google Translate API requires a proxy for bypass the CORS issue. The quick solution to overcome that issue, is using [cors-anywhere](https://github.com/Rob--W/cors-anywhere).
> 
> Currently I don't have a server to host a cors-anywhere, but there is a demo to access cors-anywhere, you can request the demo in this [site](https://cors-anywhere.herokuapp.com/corsdemo) after that you can change the proxy from http://localhost:8080 to https://cors-anywhere.herokuapp.com/
————————————————————————————


does it means
After i applyed the temporary access to the demo server
<img width="909" alt="image" src="https://github.com/Richie-Z/romajin/assets/125634462/22227c3e-fdc0-4634-af82-d157549edf99">

then copy“https://cors-anywhere.herokuapp.com/” and fills into CORS Proxy？
![image](https://github.com/Richie-Z/romajin/assets/125634462/9b13c539-2cdc-470a-8a98-79d299fdea79)
🤔️
thank you for your answer

**Comment by Richie-Z** [comment]
> > @Richie-Z Since the Spicetify extension runs in the browser then accessing Google Translate API requires a proxy for bypass the CORS issue. The quick solution to overcome that issue, is using [cors-anywhere](https://github.com/Rob--W/cors-anywhere).
> > Currently I don't have a server to host a cors-anywhere, but there is a demo to access cors-anywhere, you can request the demo in this [site](https://cors-anywhere.herokuapp.com/corsdemo) after that you can change the proxy from http://localhost:8080 to https://cors-anywhere.herokuapp.com/
> > ————————————————————————————
> 
> does it means After i applyed the temporary access to the demo server <img alt="image" width="909" src="https://private-user-images.githubusercontent.com/125634462/321516286-22227c3e-fdc0-4634-af82-d157549edf99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODY0NjYsIm5iZiI6MTcxMjg4NjE2NiwicGF0aCI6Ii8xMjU2MzQ0NjIvMzIxNTE2Mjg2LTIyMjI3YzNlLWZkYzAtNDYzNC1hZjgyLWQxNTc1NDllZGY5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQwMTQyNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDc4YWUzOTAyZTNkMzIyNWY3NzNhMjVkOGI3ODVkNWZiZGM1MGYyNTE3YmVlMDcxMGU1ZTMxZTI4ZTJkMmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZpDtfGpJkLzF2xKV8eVi98JHZH6C9vznO0CdaaIxBd8">
> 
> then copy“[https://cors-anywhere.herokuapp.com/”](https://cors-anywhere.herokuapp.com/%E2%80%9D) and fills into CORS Proxy？ ![image](https://private-user-images.githubusercontent.com/125634462/321516367-9b13c539-2cdc-470a-8a98-79d299fdea79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODY0NjYsIm5iZiI6MTcxMjg4NjE2NiwicGF0aCI6Ii8xMjU2MzQ0NjIvMzIxNTE2MzY3LTliMTNjNTM5LTJjZGMtNDcwYS04YTk4LTc5ZDI5OWZkZWE3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQwMTQyNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lN2UxNzcxMjgxMzFmZDgzOWZmYmM3ODExODM4NGVlZjFjM2ZiNWM1NDc2OTE2MWYzY2Y3MWFiMmEwOWYyMzk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-x82KNZYTrt6xFcm5Zamp-7di_4fCeFIYYy3RVOAtCY) 🤔️ thank you for your answer

yup, but remember the cors-anywhere heroku is has very limited trials. 
maybe you can use my free self-served cors-anywhere: https://web-production-05c1.up.railway.app/

**Comment by bentohere** [comment]
I've tried to fill in the CORS Proxy box with https://web-production-05c1.up.railway.app/ and https://cors-anywhere.herokuapp.com, but neither the romanji nor the translation worked. Do you know how to trigger the change?

**Comment by todayisyokult** [comment]
> I've tried to fill in the CORS Proxy box with https://web-production-05c1.up.railway.app/ and https://cors-anywhere.herokuapp.com, but neither the romanji nor the translation worked. Do you know how to trigger the change?

maybe you can try lyric plus（https://spicetify.app/docs/advanced-usage/custom-apps/#lyrics-plus）
![image](https://github.com/Richie-Z/romajin/assets/125634462/6dc7d616-557e-4005-a272-4bb08c697ecc)
or this Extensions
![image](https://github.com/Richie-Z/romajin/assets/125634462/4f5ad332-f26b-4bd0-b081-aa4c4dfaf95f)

**Comment by bentohere** [comment]
> > I've tried to fill in the CORS Proxy box with https://web-production-05c1.up.railway.app/ and https://cors-anywhere.herokuapp.com, but neither the romanji nor the translation worked. Do you know how to trigger the change?
> 
> maybe you can try lyric plus（[https://spicetify.app/docs/advanced-usage/custom-apps/#lyrics-plus）](https://spicetify.app/docs/advanced-usage/custom-apps/#lyrics-plus%EF%BC%89) ![image](https://private-user-images.githubusercontent.com/125634462/339221755-6dc7d616-557e-4005-a272-4bb08c697ecc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNTY4MjIsIm5iZiI6MTcxODI1NjUyMiwicGF0aCI6Ii8xMjU2MzQ0NjIvMzM5MjIxNzU1LTZkYzdkNjE2LTU1N2UtNDAwNS1hMjcyLTRiYjA4YzY5N2VjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwNTI4NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDVjMmM1MDJkYzljYjFiNzY0YWI3NDk2ZTc5NTc3ZDUzMmQ1MTcyOTZkNmY5YmM3NTFlOTQyMGZmNmE2NWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ISpf-gFA1UdKYK-f2Q1jNXi303kbvkkfpn5DDopvkKo) or this Extensions ![image](https://private-user-images.githubusercontent.com/125634462/339220903-4f5ad332-f26b-4bd0-b081-aa4c4dfaf95f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNTY4MjIsIm5iZiI6MTcxODI1NjUyMiwicGF0aCI6Ii8xMjU2MzQ0NjIvMzM5MjIwOTAzLTRmNWFkMzMyLWYyNmItNGJkMC1iMDgxLWFhNGM0ZGZhZjk1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwNTI4NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTJmYzliOWU1NWQ4OWYxMjRmOWZhMWI2MWEwZDkyOWQ0YjE1OWRhMGVlMDk0ZjA1YTY3ODExNDNhN2E5OGUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.68eyo2bWzvHcMrDnKJRYNTOpNffkGe3a6olgukHe1v4)

I now have the Beautiful Lyrics extension for the romanization needs. Lyrics Plus only provides translation to Chinese on mine, so I was looking for an extension that has both romanization and translation features actually works.

**Comment by Richie-Z** [comment]
> I've tried to fill in the CORS Proxy box with https://web-production-05c1.up.railway.app/ and https://cors-anywhere.herokuapp.com, but neither the romanji nor the translation worked. Do you know how to trigger the change?

I don't know if this will answering or not but I will answer it. Now to show the lyrics we must have a premium account 😢, so this extension will not works if we don't have a premium account. 

Currently working on integrating the free lyric providers to replace the current Spotify lyric provider.

**Comment by bentohere** [comment]
> > I've tried to fill in the CORS Proxy box with https://web-production-05c1.up.railway.app/ and https://cors-anywhere.herokuapp.com, but neither the romanji nor the translation worked. Do you know how to trigger the change?
> 
> I don't know if this will answering or not but I will answer it. Now to show the lyrics we must have a premium account 😢, so this extension will not works if we don't have a premium account.
> 
> Currently working on integrating the free lyric providers to replace the current Spotify lyric provider.

Thanks for the response! My account is premium already, though. I'm not sure what these all should be, but that would be very awesome if an update would fix this. It's promising after all. :D

**Comment by Richie-Z** [comment]
> > > I've tried to fill in the CORS Proxy box with https://web-production-05c1.up.railway.app/ and https://cors-anywhere.herokuapp.com, but neither the romanji nor the translation worked. Do you know how to trigger the change?
> > 
> > 
> > I don't know if this will answering or not but I will answer it. Now to show the lyrics we must have a premium account 😢, so this extension will not works if we don't have a premium account.
> > Currently working on integrating the free lyric providers to replace the current Spotify lyric provider.
> 
> Thanks for the response! My account is premium already, though. I'm not sure what these all should be, but that would be very awesome if an update would fix this. It's promising after all. :D

My account is on the free plan, so I can't figure it out what's causing this failure 😢

**Comment by ruvy03** [comment]
> > > Currently working on integrating the free lyric providers to replace the current Spotify lyric provider.

How long do you think this will take?

**Comment by Richie-Z** [comment]
**Update**: I've bought the premium, and the extension still working fine
@bentohere 

<img width="1470" alt="image" src="https://github.com/Richie-Z/romajin/assets/48403322/6d0ff23d-3476-43b2-9294-6db372c2ed00">

**Comment by Richie-Z** [comment]
> How long do you think this will take?

@DhruvSinha2003  Soon enough, maybe in the late of June or early July 🤔

**Comment by Richie-Z** [comment]
For anyone who can't see the translation, that's because the translator API need to through CORS proxy to access the functionalities. 

Currently I have made the default CORS Proxy to my free plan railway app of [cors-anywhere](https://github.com/Rob--W/cors-anywhere) (da4fcef4af76583a866d56acb041b9b58fd3b42b). But since it's on the free plan, the changes of quota has run out is high, so I advise to do self hosted [cors-anywhere](https://github.com/Rob--W/cors-anywhere) on railway.app

**Comment by bentohere** [comment]
> **Update**: I've bought the premium, and the extension still working fine @bentohere
> 
> <img alt="image" width="1470" src="https://private-user-images.githubusercontent.com/48403322/342262000-6d0ff23d-3476-43b2-9294-6db372c2ed00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTkxNDgsIm5iZiI6MTcxOTIxODg0OCwicGF0aCI6Ii80ODQwMzMyMi8zNDIyNjIwMDAtNmQwZmYyM2QtMzQ3Ni00M2IyLTkyOTQtNmRiMzcyYzJlZDAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA4NDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmOTU1MGVmM2YyNzAzOGJjNjhmZTBmYzFiOTdkZTMxODhhODU2OTBjNmZmN2QxYjhmNGEyNGJkMzAyODg4NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f-LRW0vQc8Uul9fpkxVb8vosD1AwdS8bbyLmvew62-s">

![image](https://github.com/Richie-Z/romajin/assets/172569075/194e862b-73a6-4172-abbb-f9bbff76621e)

![image](https://github.com/Richie-Z/romajin/assets/172569075/c2232810-9a0d-412b-912c-aeacadf3d869)
Thank you for the update. It just, did nothing. The link is always on the box (How do I put it, like, the link is always there; not disappear once I close the Spotify app). I've requested temporary access to https://cors-anywhere.herokuapp.com/corsdemo as well.

**Comment by Richie-Z** [comment]
Hmm, that's a weird case. Because everything that you mention supposedly it works (related to the meme: but, in my computer is works 😂).

Maybe you can send me the console message. 
To achieve this you need enable the devtools  by typing this `spicetify enable-devtools` in your terminal. 
- And then open lyric box, 
- right click to any of it, 
- and go to the console sections.

to see your saved value of the CORS proxy or any of it, you can go to Application->Local Storage->Type romajin in the filter input box
<img width="874" alt="image" src="https://github.com/Richie-Z/romajin/assets/48403322/0ce86932-4fbb-4716-80ab-e072c2347a13">

cc @bentohere

**Comment by bentohere** [comment]
> Hmm, that's a weird case. Because everything that you mention supposedly it works (related to the meme: but, in my computer is works 😂).
> 
> Maybe you can send me the console message. To achieve this you need enable the devtools by typing this `spicetify enable-devtools` in your terminal.
> 
> * And then open lyric box,
> * right click to any of it,
> * and go to the console sections.
> 
> to see your saved value of the CORS proxy or any of it, you can go to Application->Local Storage->Type romajin in the filter input box <img alt="image" width="874" src="https://private-user-images.githubusercontent.com/48403322/342283854-0ce86932-4fbb-4716-80ab-e072c2347a13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTE1NDYsIm5iZiI6MTcxOTI5MTI0NiwicGF0aCI6Ii80ODQwMzMyMi8zNDIyODM4NTQtMGNlODY5MzItNGZiYi00NzE2LTgwYWItZTA3MmMyMzQ3YTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA0NTQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMmJhMGJlZjk5MjkyYTFjOTMyM2RlMGRlMDIxNWU1MTU5ZjhkMmQyMDkwZjBmZjA0ZmUyNDc5ODFjMDg5MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5nULp1zDiKC9qUk1YAyZoj0vibxwSsPIvxMWXpPklos">
> 
> cc @bentohere

Woah, I appreciate the help! Is this it?
![image](https://github.com/Richie-Z/romajin/assets/172569075/31d0b4ce-8dd9-4f69-b20a-3fd49556245a)

![image](https://github.com/Richie-Z/romajin/assets/172569075/e4a7a888-544a-464c-92ef-e5b7efe0eb5f)

**Comment by Richie-Z** [comment]
> Woah, I appreciate the help! Is this it? ![image](https://private-user-images.githubusercontent.com/172569075/342587116-31d0b4ce-8dd9-4f69-b20a-3fd49556245a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNzUzMTMsIm5iZiI6MTcxOTM3NTAxMywicGF0aCI6Ii8xNzI1NjkwNzUvMzQyNTg3MTE2LTMxZDBiNGNlLThkZDktNGY2OS1iMjBhLTNmZDQ5NTU2MjQ1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQwNDEwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzhlOGQ4NTFkM2U2MDVmOTQ5ZjM5YjliMzU5MjViYmU1YWFhODUwOTMxYmUxNmExYTdhMDE0YWQwYmEyZDE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ilRwOyhkntgcho96MclvXpJt6j4G-Hd_6ggA8qKrPY8)
> 
> ![image](https://private-user-images.githubusercontent.com/172569075/342586757-e4a7a888-544a-464c-92ef-e5b7efe0eb5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNzUzMTMsIm5iZiI6MTcxOTM3NTAxMywicGF0aCI6Ii8xNzI1NjkwNzUvMzQyNTg2NzU3LWU0YTdhODg4LTU0NGEtNDY0Yy05MmVmLWU1YjdlZmUwZWI1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQwNDEwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODg0OGEzOTg2NmI3ZWQ1YWNjYjk4ZmQ1ZDdmOWM4MGU0OTA3MTM3NDU3Mjc5ZTBiMDFhNTNjNWJlNjk0ZGJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MexQ1wg77_AJt8E-X21IEFdiYv5TZV7OfNAqPIk547o)

Yep, that's it.
But I don't saw any error messages produced by Romajin in your console. Are the lyric box is already opened? and for make sure can you give me your installed extensions or custom apps so I can reproduce it myself

**Comment by ruvy03** [comment]
any updates on this?

**Comment by MrCheese2431** [comment]
Is there currently any easier way to do this? I've tried to do the demo and it shows up for a second and then never again.

**Comment by dedbloop101** [comment]
why is mine isnt showing translater provider??
