### ISSUE TITLE
Can't find romanji settings

### ISSUE THREAD

**Issue by AzisBasyari** [Richie-Z/romajin#5]
The romaji seems to working fine, but i need the translated lyrics.
Where do i find settings from romaji? I want to change the proxy for translate lyric but i can't find the setting.
Thank you.

Info:
Spotify for Windows (64 bit)
1.2.47.364.gf06e5cee
Spicetify v2.38.3
xpui_2024-09-20_1726857715171_f06e5ce
cef_128.4.9+g9840ad9+chromium-128.0.6613.120
Runtime: Chrome
Build System: Bazel

**Comment by TeitokuZeon** [comment]
#1

**Comment by AzisBasyari** [comment]
actually it was spicetify issue, in spicetify i mentioned, the context menu in profile did not appear and you need to update the spicetify to version 2.38.4 that support spotify 1.2.47
